import { ArrowUpRight } from 'lucide-react'
import { projects } from '../data/profile'
import { SectionHeading } from './SectionHeading'

const projectOrder = ['Infor SyteLine Customization', 'ERP Integration & Banking H2H', 'Data Migration Tools']

export function Projects() {
  const orderedProjects = [...projects].sort((a, b) => projectOrder.indexOf(a.title) - projectOrder.indexOf(b.title))
  return <section id="projects" className="section projects"><div className="container"><SectionHeading kicker="Featured projects" title="Enterprise work built around real ERP outcomes." text="Selected examples of SyteLine customization, enterprise integration, and data engineering. Expand each project to see the work behind the technology."/><div className="projects-grid">{orderedProjects.map((project, index) => <article className={`project-card project-card-${index + 1}`} data-reveal key={project.title}><div><div className="project-heading"><span className="project-index">{String(index + 1).padStart(2, '0')}</span><span className="project-label">{project.label}</span></div><h3>{project.title}</h3><p>{project.description}</p>{project.role && <p className="project-role"><strong>Role:</strong> {project.role}</p>}{project.flow && <div className="project-flow" aria-label="Integration flow">{project.flow.map((step, stepIndex) => <span key={step}>{step}{stepIndex < project.flow!.length - 1 && <b aria-hidden="true">→</b>}</span>)}</div>}{project.stack && <div className="project-stack"><small>Tech stack</small><div className="tags">{project.stack.map((technology) => <span key={technology}>{technology}</span>)}</div></div>}{project.achievements && <details className="project-details"><summary>View key achievements</summary><ul>{project.achievements.map((achievement) => <li key={achievement}>{achievement}</li>)}</ul></details>}</div><div className="project-footer"><div className="tags">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><span aria-hidden="true" className="project-arrow"><ArrowUpRight size={18}/></span></div></article>)}</div></div></section>
}
